Adilerush, in a world made as an LNP testbed.

* Beginning
Set up as normal. Farm, trade depot, workshops. 

Still had no problem. I made a seed stockpile near it, a plant stockpile, and
didn't bother linking anything.

Kitchen produced fine meals regularly, storing them in a prepared food
stockpile.

I made a temple and library.

I smoothed then engraved the dining area and bedrooms and library and temple.
Dwarves had many happy thoughts.

Set up a dormitory for migrants, and made a squad and gave them a barracks. I
picked the squad in therapist by choosing the most angry, hateful, least
imaginative, and generally shitty dwarves.

Barracks: connected via its own staircase to near the top and bottom.

* Ennui
After a couple migrant waves, I'm now at 35 dwarves. 11 years in, and
everything's been peaceful. Too peaceful.

I think I got the basic self-sufficiency thing down. None of the animals have
starved, the dwarves haven't been thirsty or hungry. Most are happy.

Made a giant room with smoothed floors. Dunno what to do with it.

* Doom

Underneath the giant room I made a smaller room with a marble door in its
entrance. This is the division between the top fort, which is sane, and the
bottom fort, which is not. Terrible things are going to happen past that door.

I want to build an atom smasher and smash my squad of shitty mean dwarves.
